name: Auto refresh site cache

# 只有推送到 main 才觸發
on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: ["main"]

jobs:
  hugo-publish:
    name: publish content to public site
    runs-on: ubuntu-latest
    steps:
      # 清除 cloudflare dns cache
      - name: clear cloudflare cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        with:
          # Using Zone Id
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}

          # Using API Token
          cf_auth: ${{ secrets.CLOUDFLARE_API_TOKEN }}

